TrajectoryPlannerROS:
  max_vel_x: 7.0
  min_vel_x: 0.5
  max_rotational_vel: 3.0
  min_in_place_vel_theta: 0.6

  acc_lim_theta: 0.2
  acc_lim_x: 0.25
  acc_lim_y: 0.0
  
  min_vel_y: 0.0
  max_vel_y: 0.0
  vy_samples: 0
  meter_scoring: true

  holonomic_robot: false
  yaw_goal_tolerance: 1.0 #0.58
  xy_goal_tolerance: 0.5  #0.25
  #goal_distance_bias: 0.8
  #path_distance_bias: 0.05
  pdist_scale: 1.5 #0.6
  gdist_scale: 0.8

  sim_time: 1.5
  heading_lookahead: 0.325
  oscillation_reset_dist: 0.05

  vx_samples: 6    #6
  vtheta_samples: 20
  dwa: false
